### PR TITLE
Ember upgrade and detection updates

### PR DESCRIPTION
**Pull request by maxwondercorn**
Major update:

* Bump Ember from 2.5 to 3.16
* Update to native classes/octane
* Updated detection for current Chrome and Safari
* Add detection for Edge Chromium
* Added tests

### CODE REVIEW

**Comment by maxwondercorn** [comment]
@djsegal Can you please send another collaborator invite?  I missed it in my inbox and it was expired when I found it.  thanks

**Comment by djsegal** [comment]
> @djsegal Can you please send another collaborator invite? I missed it in my inbox and it was expired when I found it. thanks

https://github.com/djsegal/ember-browser-checker/invitations

**Comment by djsegal** [comment]
Woooo! Congrats @maxwondercorn 🎊

**Comment by maxwondercorn** [comment]
@djsegal Can you do an npm publish or you can add me and I can release it.  npm username is gamartell. thanks

**Comment by maxwondercorn** [comment]
@djsegal see comment above

**Comment by djsegal** [comment]
done, your account on npm was actually: `gmartell` though. cheers!

**Pull request merged**
